package DTPL.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;

public class ConstraintsAspectDescriptor implements jetbrains.mps.smodel.runtime.ConstraintsAspectDescriptor {
  public ConstraintsAspectDescriptor() {
  }
  public ConstraintsDescriptor getDescriptor(SConceptId conceptId) {
    long id = conceptId.getIdValue();
    if (id == 0x2c5a37ebd022d54bL) {
      return new DijagramKonteksta_Constraints();
    }
    if (id == 0x2c5a37ebd0306fd6L) {
      return new InterfejsRefTokRefProcesRef_Constraints();
    }
    if (id == 0x2c5a37ebd022d527L) {
      return new DTPModel_Constraints();
    }
    if (id == 0x2c5a37ebd02b9082L) {
      return new Dijagram_Constraints();
    }
    if (id == 0x3fe263f784c89337L) {
      return new ProcesRefTokRefInterfejsRef_Constraints();
    }
    return new BaseConstraintsDescriptor(conceptId);
  }
}
