package DTPL.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Map;
import jetbrains.mps.smodel.adapter.ids.SReferenceLinkId;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import java.util.List;
import org.jetbrains.mps.openapi.model.SNode;
import java.util.ArrayList;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.scope.ListScope;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SNodePointer;

public class ProcesRefTokRefInterfejsRef_Constraints extends BaseConstraintsDescriptor {
  public ProcesRefTokRefInterfejsRef_Constraints() {
    super(MetaIdFactory.conceptId(0x4fade4743af4300L, 0xad5bb5d24df72c43L, 0x3fe263f784c89337L));
  }
  @Override
  protected Map<SReferenceLinkId, ReferenceConstraintsDescriptor> getNotDefaultSReferenceLinks() {
    Map<SReferenceLinkId, ReferenceConstraintsDescriptor> references = new HashMap<SReferenceLinkId, ReferenceConstraintsDescriptor>();
    references.put(MetaIdFactory.refId(0x4fade4743af4300L, 0xad5bb5d24df72c43L, 0x3fe263f784c89337L, 0x3fe263f784c8933dL), new BaseReferenceConstraintsDescriptor(MetaIdFactory.refId(0x4fade4743af4300L, 0xad5bb5d24df72c43L, 0x3fe263f784c89337L, 0x3fe263f784c8933dL), this) {
      @Override
      public boolean hasOwnScopeProvider() {
        return true;
      }
      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseScopeProvider() {
          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return breakingNode_evix3g_a0a0a0a0a1a0b0a1a1;
          }
          @Override
          public Scope createScope(final IOperationContext operationContext, final ReferenceConstraintsContext _context) {
            {
              List<SNode> nlist_tok_podatak = new ArrayList<SNode>();

              if ((SLinkOperations.getTarget(_context.getReferenceNode(), MetaAdapterFactory.getReferenceLink(0x4fade4743af4300L, 0xad5bb5d24df72c43L, 0x3fe263f784c89337L, 0x3fe263f784c8933aL, "proces_ref")) != null)) {
                SNode node_i = SLinkOperations.getTarget(_context.getReferenceNode(), MetaAdapterFactory.getReferenceLink(0x4fade4743af4300L, 0xad5bb5d24df72c43L, 0x3fe263f784c89337L, 0x3fe263f784c8933aL, "proces_ref"));
                // dijagram konteksat 
                SNode node_dk = SNodeOperations.getNodeAncestor(_context.getEnclosingNode(), MetaAdapterFactory.getConcept(0x4fade4743af4300L, 0xad5bb5d24df72c43L, 0x2c5a37ebd022d54bL, "DTPL.structure.DijagramKonteksta"), false, false);
                for (SNode node_dtpeitp : SLinkOperations.getChildren(node_dk, MetaAdapterFactory.getContainmentLink(0x4fade4743af4300L, 0xad5bb5d24df72c43L, 0x2c5a37ebd022d54bL, 0x2c5a37ebd02362caL, "dtp_element_interfejs_tok"))) {
                  for (SNode node_pti : SLinkOperations.getChildren(node_dtpeitp, MetaAdapterFactory.getContainmentLink(0x4fade4743af4300L, 0xad5bb5d24df72c43L, 0x2c5a37ebd02362c7L, 0x2c5a37ebd02561daL, "out_proces_tok_interfejs"))) {
                    SNode node_p = (SNode) SLinkOperations.getTarget(node_pti, MetaAdapterFactory.getReferenceLink(0x4fade4743af4300L, 0xad5bb5d24df72c43L, 0x2c5a37ebd024fa9aL, 0x2c5a37ebd0256147L, "proces_ref"));
                    ListSequence.fromList(nlist_tok_podatak).addElement(SLinkOperations.getTarget(node_pti, MetaAdapterFactory.getContainmentLink(0x4fade4743af4300L, 0xad5bb5d24df72c43L, 0x2c5a37ebd024fa9aL, 0x2c5a37ebd024fa9dL, "tok_podataka")));
                  }


                }


              }
              return new ListScope(nlist_tok_podatak) {
                public String getName(SNode child) {
                  SNode node_i = (SNode) child;
                  return SPropertyOperations.getString(node_i, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
                }
              };

            }
          }
        };
      }
    });
    references.put(MetaIdFactory.refId(0x4fade4743af4300L, 0xad5bb5d24df72c43L, 0x3fe263f784c89337L, 0x3fe263f784c89338L), new BaseReferenceConstraintsDescriptor(MetaIdFactory.refId(0x4fade4743af4300L, 0xad5bb5d24df72c43L, 0x3fe263f784c89337L, 0x3fe263f784c89338L), this) {
      @Override
      public boolean hasOwnScopeProvider() {
        return true;
      }
      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseScopeProvider() {
          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return breakingNode_evix3g_a0a0a0a0a1a0b0a2a1;
          }
          @Override
          public Scope createScope(final IOperationContext operationContext, final ReferenceConstraintsContext _context) {
            {
              List<SNode> nlist_interfejs = new ArrayList<SNode>();

              if ((SLinkOperations.getTarget(_context.getReferenceNode(), MetaAdapterFactory.getReferenceLink(0x4fade4743af4300L, 0xad5bb5d24df72c43L, 0x3fe263f784c89337L, 0x3fe263f784c8933dL, "tok_podataka_ref")) != null)) {


                SNode node_dk = SNodeOperations.getNodeAncestor(_context.getEnclosingNode(), MetaAdapterFactory.getConcept(0x4fade4743af4300L, 0xad5bb5d24df72c43L, 0x2c5a37ebd022d54bL, "DTPL.structure.DijagramKonteksta"), false, false);
                for (SNode node_dtpeitp : SLinkOperations.getChildren(node_dk, MetaAdapterFactory.getContainmentLink(0x4fade4743af4300L, 0xad5bb5d24df72c43L, 0x2c5a37ebd022d54bL, 0x2c5a37ebd02362caL, "dtp_element_interfejs_tok"))) {
                  for (SNode node_pti : SLinkOperations.getChildren(node_dtpeitp, MetaAdapterFactory.getContainmentLink(0x4fade4743af4300L, 0xad5bb5d24df72c43L, 0x2c5a37ebd02362c7L, 0x2c5a37ebd02561daL, "out_proces_tok_interfejs"))) {
                    SNode node_tp = (SNode) SLinkOperations.getTarget(node_pti, MetaAdapterFactory.getContainmentLink(0x4fade4743af4300L, 0xad5bb5d24df72c43L, 0x2c5a37ebd024fa9aL, 0x2c5a37ebd024fa9dL, "tok_podataka"));
                    if (SPropertyOperations.getString(node_tp, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals(SPropertyOperations.getString(SLinkOperations.getTarget(_context.getReferenceNode(), MetaAdapterFactory.getReferenceLink(0x4fade4743af4300L, 0xad5bb5d24df72c43L, 0x3fe263f784c89337L, 0x3fe263f784c8933dL, "tok_podataka_ref")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")))) {
                      ListSequence.fromList(nlist_interfejs).addElement(SLinkOperations.getTarget(node_pti, MetaAdapterFactory.getReferenceLink(0x4fade4743af4300L, 0xad5bb5d24df72c43L, 0x2c5a37ebd024fa9aL, 0x2c5a37ebd0256146L, "interfejs_ref")));
                    }
                  }


                }

              }

              return new ListScope(nlist_interfejs) {
                public String getName(SNode child) {
                  SNode node_i = (SNode) child;
                  return SPropertyOperations.getString(node_i, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
                }
              };

            }
          }
        };
      }
    });
    return references;
  }
  private static SNodePointer breakingNode_evix3g_a0a0a0a0a1a0b0a1a1 = new SNodePointer("r:d1323bac-5479-4158-b8f2-09045725c39d(DTPL.constraints)", "4603351683862128329");
  private static SNodePointer breakingNode_evix3g_a0a0a0a0a1a0b0a2a1 = new SNodePointer("r:d1323bac-5479-4158-b8f2-09045725c39d(DTPL.constraints)", "4603351683862367144");
}
