package DTPL.typesystem;

/*Generated by MPS */

import jetbrains.mps.errors.QuickFix_Runtime;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class XXX_QuickFix extends QuickFix_Runtime {
  public XXX_QuickFix() {
    super(new SNodePointer("r:20c5195e-19a6-4b26-9fce-472e3335fbcc(DTPL.typesystem)", "3195928371525059729"));
  }
  public void execute(SNode node) {
    SPropertyOperations.set(((SNode) XXX_QuickFix.this.getField("dtp_models")[0]), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "IME");
  }
}
