package DTPL.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class InterfejsTokProces_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {

  @Override
  public String getConceptFqName() {
    return "DTPL.structure.InterfejsTokProces";
  }

}
