package DTPL.actions;

/*Generated by MPS */

import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class node_factories_Dijagram {
  public static class NodeFactory_3195928371522202942 implements NodeFactory {
    public void setup(SNode newNode, SNode sampleNode, SNode enclosingNode, SModel model) {
      SPropertyOperations.set(newNode, MetaAdapterFactory.getProperty(0x4fade4743af4300L, 0xad5bb5d24df72c43L, 0x2c5a37ebd02b9082L, 0x2c5a37ebd02b9083L, "level"), "" + (0));
      {
        final SNode dk = enclosingNode;
        if (SNodeOperations.isInstanceOf(dk, MetaAdapterFactory.getConcept(0x4fade4743af4300L, 0xad5bb5d24df72c43L, 0x2c5a37ebd022d54bL, "DTPL.structure.DijagramKonteksta"))) {
          SLinkOperations.setTarget(newNode, MetaAdapterFactory.getReferenceLink(0x4fade4743af4300L, 0xad5bb5d24df72c43L, 0x2c5a37ebd02b9082L, 0x2c5a37ebd02d4604L, "koji_se_dekomponuje_proces_ref"), SLinkOperations.getTarget(dk, MetaAdapterFactory.getContainmentLink(0x4fade4743af4300L, 0xad5bb5d24df72c43L, 0x2c5a37ebd022d54bL, 0x2c5a37ebd022d54cL, "proces")));
          SPropertyOperations.set(newNode, MetaAdapterFactory.getProperty(0x4fade4743af4300L, 0xad5bb5d24df72c43L, 0x2c5a37ebd02b9082L, 0x2c5a37ebd02b9083L, "level"), "" + (1));
        }
      }
      if (SPropertyOperations.getInteger(newNode, MetaAdapterFactory.getProperty(0x4fade4743af4300L, 0xad5bb5d24df72c43L, 0x2c5a37ebd02b9082L, 0x2c5a37ebd02b9083L, "level")) == 0) {
        SNode node_d = (SNode) enclosingNode;
        SPropertyOperations.set(newNode, MetaAdapterFactory.getProperty(0x4fade4743af4300L, 0xad5bb5d24df72c43L, 0x2c5a37ebd02b9082L, 0x2c5a37ebd02b9083L, "level"), "" + (SPropertyOperations.getInteger(node_d, MetaAdapterFactory.getProperty(0x4fade4743af4300L, 0xad5bb5d24df72c43L, 0x2c5a37ebd02b9082L, 0x2c5a37ebd02b9083L, "level")) + 1));
      }
    }
  }
}
