package DTPL.actions;

/*Generated by MPS */

import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class node_factories_ProcesRefTokRefInterfejsRef {
  public static class NodeFactory_4603351683861949704 implements NodeFactory {
    public void setup(SNode newNode, SNode sampleNode, SNode enclosingNode, SModel model) {
      {
        final SNode dtpep = enclosingNode;
        if (SNodeOperations.isInstanceOf(dtpep, MetaAdapterFactory.getConcept(0x4fade4743af4300L, 0xad5bb5d24df72c43L, 0x2c5a37ebd02dce72L, "DTPL.structure.DTPElementProces"))) {
          SNode node_p = SLinkOperations.getTarget(dtpep, MetaAdapterFactory.getContainmentLink(0x4fade4743af4300L, 0xad5bb5d24df72c43L, 0x2c5a37ebd02dce72L, 0x2c5a37ebd02dce73L, "proces"));

          SLinkOperations.setTarget(newNode, MetaAdapterFactory.getReferenceLink(0x4fade4743af4300L, 0xad5bb5d24df72c43L, 0x3fe263f784c89337L, 0x3fe263f784c8933aL, "proces_ref"), node_p);
        }
      }
    }
  }
}
